language: cpp

sudo: false

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then
      brew update;
    fi;

install:
  - if [ $TRAVIS_OS_NAME = linux -a "$CXX" = "g++" ]; then
        export CXX=g++-4.8;
    elif [ $TRAVIS_OS_NAME = osx ]; then
       brew outdated boost || brew upgrade boost;
    fi;

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.8-dev
      - g++-4.8
      - libncursesw5-dev
      - libboost-regex-dev

script: cd src && make && make test
