language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y 
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -y libstdc++-4.8-dev; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -y g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX=g++-4.8; fi
  - sudo apt-get install -y libncursesw5-dev
  - sudo apt-get install -y libboost-regex1.54-dev
script: cd src && make && make test
