name: Bug report
description: Report an unexpected behaviour with the editor
labels: bug
title: "[BUG] "
body:

    - type: input
      attributes:
          label: "Version of Kakoune"
          description: "If unsure, use the output of command: `kak -version`"
          placeholder: "v2020.12.31"
      validations:
          required: true

    - type: textarea
      attributes:
          label: "Reproducer"
          description: "What are the steps to follow to reproduce the issue?"
          placeholder: |
              If any specific configuration or environment settings are required to reproduce the issue, also describe them here.
      validations:
        required: true

    - type: textarea
      attributes:
          label: "Outcome"
          description: "What is the outcome of the reproducing steps above?"
      validations:
        required: true

    - type: textarea
      attributes:
          label: "Expectations"
          description: "What was the expected outcome of the reproducing steps above?"
      validations:
        required: true

    - type: textarea
      attributes:
          label: "Additional information"
          description: "Any other information that may be relevant to diagnosing the issue should be documented here"
          placeholder: |
              Examples of relevant information:

              * What OS and distribution are you using?
              * Are you running an experimental branch (i.e. not `master`)?
              * Is the issue reproducible in other terminals?
      validations:
        required: false
